In [2]:
import yfinance as yf
from yahoo_fin import stock_info as si
from pandas_datareader import data as pdr

In [11]:
hourly_data = yf.download('TSLA', period="365d", interval='1d')

[*********************100%***********************]  1 of 1 completed

In [12]:
hourly_data['34 EMA'] = hourly_data['Adj Close'].ewm(min_periods=34, adjust=False, alpha =(2/35)).mean().round(2)
hourly_data['50 EMA'] = hourly_data['Adj Close'].ewm(min_periods=50,adjust=False,alpha=(2/50)).mean().round(2)

In [13]:
df = hourly_data.tail(315)

In [14]:
capital = 100000
invested = False

In [15]:
df

,Open,High,Low,Close,Adj Close,Volume,34 EMA,50 EMA
Date,,,,,,,,
2019-12-30,85.758003,85.800003,81.851997,82.940002,82.940002,62932000,73.32,70.23
2019-12-31,81.000000,84.258003,80.416000,83.666000,83.666000,51428500,73.91,70.77
2020-01-02,84.900002,86.139999,84.342003,86.052002,86.052002,47660500,74.61,71.38
2020-01-03,88.099998,90.800003,87.384003,88.601997,88.601997,88892500,75.41,72.07
2020-01-06,88.094002,90.311996,88.000000,90.307999,90.307999,50665000,76.26,72.80
...,...,...,...,...,...,...,...,...
2021-03-24,667.909973,668.020020,630.109985,630.270020,630.270020,33795200,700.24,704.09
2021-03-25,613.000000,645.500000,609.500000,640.390015,640.390015,39224900,696.82,701.54
2021-03-26,641.869995,643.820007,599.890015,618.710022,618.710022,33778400,692.36,698.23
2021-03-29,615.640015,616.479980,596.020020,611.289978,611.289978,28599400,687.73,694.75
2021-03-30,601.750000,633.500000,591.010010,618.760010,618.760010,25935891,683.79,691.71

In [16]:
#determine uptrend  or downtrend based on EMAs
df['bullish'] = df['34 EMA'] > df['50 EMA']

<ipython-input-16-8ed16fc93ac2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bullish'] = df['34 EMA'] > df['50 EMA']

In [17]:
#see only uptrend periods
df[df['34 EMA'] > df['50 EMA']]

,Open,High,Low,Close,Adj Close,Volume,34 EMA,50 EMA,bullish
Date,,,,,,,,,
2019-12-30,85.758003,85.800003,81.851997,82.940002,82.940002,62932000,73.32,70.23,True
2019-12-31,81.000000,84.258003,80.416000,83.666000,83.666000,51428500,73.91,70.77,True
2020-01-02,84.900002,86.139999,84.342003,86.052002,86.052002,47660500,74.61,71.38,True
2020-01-03,88.099998,90.800003,87.384003,88.601997,88.601997,88892500,75.41,72.07,True
2020-01-06,88.094002,90.311996,88.000000,90.307999,90.307999,50665000,76.26,72.80,True
...,...,...,...,...,...,...,...,...,...
2021-03-11,699.400024,702.500000,677.179993,699.599976,699.599976,36253900,721.81,719.11,True
2021-03-12,670.000000,694.880005,666.140015,693.729980,693.729980,33583800,720.20,718.10,True
2021-03-15,694.090027,713.179993,684.039978,707.940002,707.940002,29335600,719.50,717.69,True
2021-03-16,703.349976,707.919983,671.000000,676.880005,676.880005,31903400,717.07,716.06,True
2021-03-17,656.869995,703.729980,651.010010,701.809998,701.809998,40083300,716.19,715.49,True